My_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('herokuapp.urls')),    
    path('',include('herokuapp2.urls')),
    path('',include('matakuliah.urls')),
    path('',include('story6.urls')),
    path('',include('story8.urls')),
    path('',include('story82.urls')),
    path('',include('story9.urls')),
]

matakuliah/urls.py
from django.urls import path

from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('ListMataKuliah', views.Utama, name='matakuliah_list'),
    path('FormMataKuliah',views.formMatkul, name='matakuliah_form'),
    path('<int:id>',views.matkulDetail),
    path('deleteMataKuliah/<str:id>', views.deleteMatkul,name="matakuliah_delete"),
    path('UpdateMataKuliah/<str:id>',views.updateMatkul,name="matakuliah_update")
]

matakuliah/models.py
from django.db import models

# Create your models here.
class MataKuliahSaya(models.Model):
    nama = models.CharField(max_length = 100)
    dosen = models.CharField(max_length = 100)
    jumlahSKS = models.PositiveIntegerField()
    semester = models.CharField(max_length = 100)
    ruangKelas = models.CharField(max_length= 100)
    deskripsi = models.CharField(max_length = 500)

    def __str__(self):
        return self.nama

matakuliah/forms.py
from django import forms

from .models import MataKuliahSaya

class MataKuliahForm(forms.ModelForm):
    nama = forms.CharField()
    dosen = forms.CharField()
    jumlahSKS = forms.IntegerField()
    semester = forms.CharField()
    ruangKelas = forms.CharField()
    deskripsi = forms.CharField()

    class Meta:
        model = MataKuliahSaya
        fields = '__all__'

matakuliah/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import MataKuliahSaya
from .forms import MataKuliahForm

# Create your views here.
def Utama(request):
    matahkuliahs = MataKuliahSaya.objects.all()
    return render(request, 'matakuliah/matakuliah_list.html', {'matakuliahs':matahkuliahs} )

def formMatkul(request):
    form = MataKuliahForm()
    if request.method == 'POST':
        form = MataKuliahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ListMataKuliah')

    return render(request, 'matakuliah/matakuliah_forms.html',{'form':form})

def matkulDetail(request,id):
    matakuliah = MataKuliahSaya.objects.get(id=id)
    return render(request,'matakuliah/matakuliah_detail.html',{'matakuliah':matakuliah})

def deleteMatkul(request,id):
    item = MataKuliahSaya.objects.get(id=id)
    if request.method == 'POST' :
        item.delete()
        return redirect('/ListMataKuliah')

    return render(request, 'matakuliah/matakuliah_delete.html',{'item':item})

def updateMatkul(request,id):
    matakuliah = MataKuliahSaya.objects.get(id=id)
    form = MataKuliahForm(instance=matakuliah)
    if request.method == 'POST':
        form = MataKuliahForm(request.POST, instance=matakuliah)
        if form.is_valid():
            form.save()
            return redirect('/ListMataKuliah')
    context = {
        'form' :form
    }
    return render (request,'matakuliah/matakuliah_forms.html' ,context)

matakuliah/templates/matakuliah/matakuliah_delete.html
{% extends 'base.html' %}
{% load static %}
{% block head-footer %}
<header>
  <div class="cover" style="background-image: url(static/huhu.png);">
</header>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Delete course</b></h2>
        <hr class="mt-0 mb-4">
        
        <form action="{% url 'matakuliah:matakuliah_delete' item.id %}" method='POST'>
            {% csrf_token %}
            <h5 class="featurette-heading">Do you want to delete the course "{{item}}"?</h5>
            <br>
            <button type="submit" class="btn btn-danger"><b>Yes</b></button>
            <a type="button" class="btn btn-info" href="{% url 'matakuliah:matakuliah_list' %}"><b>Cancel</b></a>

      </div>
    </div>
  </div>
<br>

{% endblock %}

matakuliah/templates/matakuliah/matakuliah_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head-footer %}
<header>
  <div class="cover" style="background-image: url(static/huhu.png);">
</header>
<br>>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Course Detail</b></h2>
        <table class="table" style="text-align: left;" >
        <tbody >
          <tr>
            <th scope="row">Name</th>
            <td>{{ matakuliah.nama }}</td>
          </tr>
          <tr>
            <th scope="row">Lecturer</th>
            <td>{{ matakuliah.dosen }}</td>
          </tr>
          <tr>
            <th scope="row">Credit</th>
            <td>{{ matakuliah.jumlahSKS }}</td>
          </tr>
          <tr>
            <th scope="row">Semester</th>
            <td>{{ matakuliah.semester }}</td>
          </tr>
          <tr>
            <th scope="row">Room</th>
            <td>{{ matakuliah.ruangKelas }}</td>
          </tr>
          <tr>
            <th scope="row">Deskripsi</th>
            <td>{{ matakuliah.deskripsi }}</td>
          </tr>
        </tbody>
      </table>
      <a button type="button" class="btn btn-outline-primary" href="{% url 'matakuliah:matakuliah_update' matakuliah.id %}">Update Course</a>
      <a class="btn btn-danger" href="{% url 'matakuliah:matakuliah_delete' matakuliah.id %}">Delete Course</a>
      <a type="button" class="btn btn-light" href="{% url 'matakuliah:matakuliah_list' %}"><b>Back</b></a>
  </div>
</div>
</div>
</br>
{% endblock %}

matakuliah/templates/matakuliah/matakuliah_forms.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head-footer %}
<header>
  <div class="cover" style="background-image: url(static/huhu.png);">
</header>
<br>
<div class="container">
    <!-- <div class="row justify-content-center">
      <div class="col-8"> -->
        <h2 class="featurette-heading"><b>Add course</b></h2>
        <hr class="mt-0 mb-4">
        <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-light" href="{% url 'matakuliah:matakuliah_list' %}"><b>Back</b></a>
        </form>
        <br>
      </div>
    </div>
  </div>
<br>
{% endblock %}

matakuliah/templates/matakuliah/matakuliah_list.html
{% extends 'base.html' %}
{% load static %}
{% block head-footer %}
<header>
  <div class="cover" style="background-image: url(static/huhu.png);">
</header>
<br>
    <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>My Courses</b></h2>
        <hr class="mt-0 mb-4">
        <div class="list-group">
            {% for i in matakuliahs %}
            <a href="{{ i.id }}" class="list-group-item list-group-item-action mute-bg"><b>{{ i.nama }}</b></a>
            {% endfor %}
        </div>
        <br>
        <a class="btn btn-dark" href="{% url 'matakuliah:matakuliah_form' %}"><b>Add course</b></a>
      <br>
    </div>
  </div>
</div>
<br>


{% endblock %}