My_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('herokuapp.urls')),    
    path('',include('herokuapp2.urls')),
    path('',include('matakuliah.urls')),
    path('',include('story6.urls')),
    path('',include('story8.urls')),
    path('',include('story82.urls')),
    path('',include('story9.urls')),
]

story82/urls.py
from django.urls import path

from . import views

app_name = 'story82'

urlpatterns = [
    path('bookfinder2', views.utama, name='daftar_buku2'),
    path('getBooks',views.searchBook,name="getBooks"),
]

story82/models.py
from django.db import models

# Create your models here.

story82/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers

import requests

# Create your views here.
def utama(request):
    return render(request,'story82/story82.html')

def searchBook(request):
    if(request.is_ajax()):
        response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['fname'])
        data = response.json()
        return JsonResponse(data)

story82/templates/story82/story82.html
{% extends 'base.html' %}
{% load static %}
{% block head-footer %}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<header> 
    <div class="cover" style="background-image: url(static/Group23.png);">
    </div>
</header>

<body>
    <div class="container">
        <div class="container-fluid">
            <h1 id="atas" style="text-align: center; margin-top: 20px;">Book Finder</h1>
            <div style="text-align: center;">
                <input type="text" id="searchArea" name="fname" placeholder="Nama Buku"><br ><br>
            </div>
            <!-- <button type="button" class="btn btn-primary" id="searchButton">Search</button> -->
            <section id="list_books">
            </section>
        </div>
    </div>
</body>
<script>
    var buku_url = "{% url 'story82:getBooks' %}?fname=";
</script>
<script type="text/javascript" src="{% static 'desain/js/bookfinder2.js' %}"></script>


{% endblock %}