My_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('herokuapp.urls')),    
    path('',include('herokuapp2.urls')),
    path('',include('matakuliah.urls')),
    path('',include('story6.urls')),
    path('',include('story8.urls')),
    path('',include('story82.urls')),
    path('',include('story9.urls')),
]

herokuapp/urls.py
from django.urls import path

from . import views

app_name = 'herokuapp'

urlpatterns = [
    path('', views.page1),
    path('portofolio',views.page2 , name='portofolio'),
]

herokuapp2/urls.py
from django.urls import path

from . import views

app_name = 'herokuapp2'

urlpatterns = [
    path('story1', views.page1, name='story1'),
]

matakuliah/urls.py
from django.urls import path

from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('ListMataKuliah', views.Utama, name='matakuliah_list'),
    path('FormMataKuliah',views.formMatkul, name='matakuliah_form'),
    path('<int:id>',views.matkulDetail),
    path('deleteMataKuliah/<str:id>', views.deleteMatkul,name="matakuliah_delete"),
    path('UpdateMataKuliah/<str:id>',views.updateMatkul,name="matakuliah_update")
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('daftar/', views.daftar, name='daftar'),
    path('hapus/', views.hapus, name="hapus"),
    path('ListKegiatan', views.Utama, name='kegiatan_list'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('bookfinder', views.utama, name='daftar_buku'),
]

story82/urls.py
from django.urls import path

from . import views

app_name = 'story82'

urlpatterns = [
    path('bookfinder2', views.utama, name='daftar_buku2'),
    path('getBooks',views.searchBook,name="getBooks"),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('login',views.loginAkun,name="login"),
    path('register',views.register, name="register"),
    path('logout',views.logoutAkun, name="logout")
]

herokuapp/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class KegiatanSaya(models.Model):
    NamaKegiatan = models.CharField(max_length=500)
    Deskripsi = models.TextField(max_length=500)
    def __str__(self):
        return self.NamaKegiatan + self.Deskripsi   

class Participant(models.Model):
    name = models.CharField(max_length = 200)
    kegiatan = models.ForeignKey(KegiatanSaya, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.kegiatan) + " dan " + self.name

story8/models.py
from django.db import models

# Create your models here.

story82/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import *

class KegiatanForm(forms.ModelForm):
    NamaKegiatan = forms.CharField()
    Deskripsi = forms.Textarea()
    class Meta:
        model = KegiatanSaya
        fields = '__all__'

class ParticipantForm(forms.ModelForm):
    class Meta:
        model =  Participant
        fields = '__all__'

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


# from .models import order

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

herokuapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def page1(request):
    return render(request, 'herokuapp/index.html')

def page2(request):
    return render(request,'herokuapp/portofolio.html')

herokuapp2/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def page1(request):
    return render(request, 'herokuapp2/story1.html')

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def Utama(request):
    kegiatans = KegiatanSaya.objects.all()
    participants = Participant.objects.all()
    keg_par = []
    for kegiatan in kegiatans:
        kegiatan_partic = []
        for participant in participants:
            if (str(participant.kegiatan) == str(kegiatan)):
                kegiatan_partic.append(participant)
        keg_par.append((kegiatan,kegiatan_partic))
    
    context = {
        "hasil_list" : keg_par
    }
    return render(request, 'story6/kegiatan_list.html', context )

def daftar(request):
    id_kegiatan = request.POST.get('id_kegiatan', None)
    name_participant = request.POST.get('name_participant',None)
    nama_kegiatan = request.POST.get('nama_kegiatan', None)
    deskripsi_kegiatan = request.POST.get('deskripsi_kegiatan', None)

    if (id_kegiatan and name_participant) :
        Participant.objects.create(name=name_participant, kegiatan=KegiatanSaya.objects.get(id = id_kegiatan))
    else:
        KegiatanSaya.objects.create(NamaKegiatan=nama_kegiatan, Deskripsi=deskripsi_kegiatan)

    return redirect('/ListKegiatan')

def hapus(request):
    id_participant = request.POST.get('id_participant', None)
    participant = Participant.objects.get(id = id_participant)
    participant.delete()
    return redirect('/ListKegiatan')

story8/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

def utama(request):
    return render(request,'story8/story8.html')

story82/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers

import requests

# Create your views here.
def utama(request):
    return render(request,'story82/story82.html')

def searchBook(request):
    if(request.is_ajax()):
        response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['fname'])
        data = response.json()
        return JsonResponse(data)

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm

def loginAkun(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("MASUK ELSE")
            messages.error(request,"wrong username or password")

    return render(request,'story9/login.html')



def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    context = {'form': form}
    return render(request,'story9/register.html',context)

def logoutAkun(request):
    logout(request)
    return redirect('/login')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Aryaputra Athallah</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel = "icon" type = "image/png" href = "{% static 'image/AR.png' %}">
  <link rel="stylesheet" href="{% static 'desain/css/styles.css' %}"/>
  <script type="text/javascript" src="{% static 'desain/js/jquery.js' %}"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
</head>
<body>
<div class="navigasi">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #3E4D5E;">
    <a class="navbar-brand" href="/" style="font-style: italic;">AR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a style="color: white;" class="nav-link"href="{% url 'herokuapp:portofolio' %}">Portofolio</a>
        </li>
        <li class="nav-item">
          <a style="color: white;" class="nav-link" href="{% url 'herokuapp2:story1' %}">Story1</a></li></a>
        </li>    
        <li class="nav-item">
          <a style="color: white;" class="nav-link" href="{% url 'matakuliah:matakuliah_list' %}">Course</a></li>
        </li>
        <li class="nav-item">
          <a style="color: white;" class="nav-link" href="{% url 'story6:kegiatan_list' %}">Activity</a></li>
        </li>
        <li class="nav-item">
          <a style="color: white;" class="nav-link" href="{% url 'story8:daftar_buku' %}">Story 8</a></li>
        </li>
        <li class="nav-item">
          <a style="color: white;" class="nav-link" href="{% url 'story82:daftar_buku2' %}">Story 8(2)</a></li>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a style="color: white; font-weight: bold;" class="nav-link" href="/">Hello, {{request.user}}</a></li>
      </li>
     
      <li class="nav-item">
        <a style="color: white; font-weight: bold;" class="nav-link" href="{% url 'story9:logout' %}">Logout</a></li>
      </li>
      {% else %}

      <li class="nav-item">
        <a style="color: white; font-weight: bold;" class="nav-link" href="{% url 'story9:login' %}">Login</a></li>
      </li>
      <li class="nav-item">
        <a style="color: white; font-weight: bold;" class="nav-link" href="{% url 'story9:register' %}">SignUp</a></li>
      </li>
      {% endif %}
    </ul>  
</div>
</nav>

{% block head-footer %}

{% endblock %}

<footer>
    <div class="penutup" style="background-image: url(static/Group2.png);">
    <h1>Contact Me</h1>
    <p style="text-align: center;"><a href="https://www.instagram.com/aryaputra213/">
        <img class="icon" src="{% static 'image/about/instagram.png' %}" class="img-fluid" alt="Responsive image" > 
        <a href="https://www.linkedin.com/in/aryaputra-athallah-63b5a3199/">
        <img class="icon" src="{% static 'image/linkedin.png' %}" style= "padding-left: 20px;" class="img-fluid" alt="Responsive image"></a>
    </p>
    <p class="cr">Copyright © 2020 Arya, All right reserved</p>
    </div>
</footer>
</html>